server:
  port: 7001
  error:
    include-message: always
spring:
  data:
    mongodb:
      host: 123.213.1.211
      port: 27017
      database: product-db
logging:
  level:
    root: INFO
    com.psc.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG